### ISSUE TITLE
[PE-D][Tester B] Restrictions on a person's name does not allow for the adding of some legal names

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-4/tp#141]
For example, “John-Doe” and “Tan Mei Ling, Jane” are not allowed, but legal names can have commas and hyphens. 

![Screenshot 2023-11-03 at 4.36.00 PM.png](https://raw.githubusercontent.com/sunzihan23/ped/main/files/5fd1bc16-fdbe-48dc-a92a-1c9cba073a0f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sunzihan23/ped#3

**Comment by tayian** [comment]
Thank you for the feedback. This restriction is in place to ensure uniformity and prevent issues with data entry, retrieval, or display in Connectify, ensuring a smooth and consistent user experience. While restrictive to the user, such limitations are in place to avoid complications and ensure the accurate handling of data.
