### ISSUE TITLE
[PE-D][Tester D] Address recognized as tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-4/tp#150]
When adding an address with t/ inside the address, it is recognized as a tag. 
![Screenshot 2023-11-03 at 16.44.35.png](https://raw.githubusercontent.com/wjacobw/ped/main/files/b5c439d7-b3bc-4528-8ce5-52feda75fece.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wjacobw/ped#3

**Comment by geraldngjx** [comment]
It is unlikely that address would contain a t/ tag or any other placeholders that we have used in the command format, hence we did not account for that during command execution.
