### ISSUE TITLE
[PE-D][Tester B] All command words are case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-4/tp#153]
For example, only “addPerson” is allowed while “addperson” is not recognised as a command word. There is probably no need for case sensitivity enforcements for command words as forcing the capitalisation of certain letters can result in app not being optimised for fast typists. 

![Screenshot 2023-11-03 at 4.46.38 PM.png](https://raw.githubusercontent.com/sunzihan23/ped/main/files/53896989-9bd2-4d7b-8f00-b3530ae575a2.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sunzihan23/ped#6

**Comment by geraldngjx** [comment]
It would not affect the speed of typing much by including an additional capital letter, hence we did not take "addperson" as an alternative to the "addPerson" command. Another benefit is the increased readability of using camelCase for the command keyword, thus we feel that there is not a need to accept "addperson" as a command too.
