### ISSUE TITLE
[PE-D][Tester D] Wrong feedbacks for rank command when there is no person in the list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-4/tp#163]
![Screenshot 2023-11-03 at 16.52.31.png](https://raw.githubusercontent.com/wjacobw/ped/main/files/c7b66ad5-a423-41e3-9a5c-7804045c6cea.png)
When using the rank command and there is no people, it should be person instead of persons

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wjacobw/ped#5

**Comment by tayian** [comment]
Rejected. While "There are no persons" sounds weird, it is perfectly valid English, and is consistent with our naming that there are Person objects (with which a valid plural would be "Persons").
