### ISSUE TITLE
[PE-D][Tester B] Able to click on some UI elements but nothing occurs after clicking on them

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-4/tp#183]
Users may be confused by this ability to click on things like a company when nothing happens after the click, especially since the app has many elements that actually respond to clicks, like the tabs. 

![Screenshot 2023-11-03 at 7.03.32 PM.png](https://raw.githubusercontent.com/sunzihan23/ped/main/files/6d4e9961-02f4-47b8-9cb8-b702cb1bfc85.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: sunzihan23/ped#19

**Comment by geraldngjx** [comment]
We feel that this does not cause confusion to the user and instead allow them to select the company whose details they wish to reference, hence we did not remove the clickable nature of the UI as we felt that it is an additional benefit.
